Collection contract
sarcophagus-org/governance-incentives-contract pull request #1
Opened 2022-09-29 09:19 UTC by solidoracle

### Overview

Created Collection contract responsible for custody of Sarcophagus fees collected via protocol fees, as well as the distribution of those fees to reward and incentivise voters on Sarcophagus Dao proposals.

Smart contract and testing completed.

### To do
Build a complex scenario to further test the smart contract behaviour

2022-09-30 11:31 UTC, DarksightKellar requested changes
Great job @solidoracle!

I know I've left a bunch of comments here but a lot of them are simple rename suggestions. Really most of them are minor edits in general, although I'd like them to be addressed before... the merge.

Of course if there are any you'd rather handle in a follow up PR feel free to push back in a reply or on standup.

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/libraries/LibErrors.sol
> +// SPDX-License-Identifier: Unlicense
Is this file no longer needed? Could be deleted

2022-09-30 11:31 UTC, DarksightKellar commented on test/utils/helpers.ts
> +let zero = ethers.constants.Zero;
I would suggest getting into the habit of defaulting to `const` variables, and only changing to `let` (or whatever keyword the language uses to indicate "changeable" variables) only if you later realise you need to update the variable.

Constants generally have low-level optimisations built in for them -- and prevent accidental updates by future developers

2022-09-30 11:31 UTC, DarksightKellar commented on test/utils/helpers.ts
> +export function sum(rewards: any) {
Could you use an actual type here for `rewards`?

2022-09-30 11:31 UTC, DarksightKellar commented on test/utils/helpers.ts
> +      sum = sum.add(rewards[i][1]);
Related to my comment above -- typing `rewards` will probably expose logical issues in the code here that will need fixing.

It's entirely possible there's actually no issue here, and I simply don't understand the structure that leads to using `rewards[i][1]` -- but a definite type of `rewards` will resolve that

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +    event Rewards(Reward[]);
Could this be updated to something like `event AllocateRewards(Reward[] rewards)`?

---

On a related point, using more descriptive names, like you have in many other areas, often removes the need to add comments/docs to every variable, as it is self-documenting.

I'd suggest limiting doc comments generally to function and contract descriptions, and only adding comments to clarify code that isn't immediately obvious at a glance.

The comment on `balanceOf` is fine in my opinion since it's being used in a slightly non-standard way, so that extra tip is useful, but most of the doc comments on single line declarations seem redundant and can be removed without sacrificing anything -- as long as the names are descriptive enough.

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +    event Claim(address _address, uint claimAmount);
Suggest renaming `Claim` -> `ClaimRewards`, which will remove the need for doc comment above

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +    event Withdraw(address _address, uint withdrawAmount);
Suggest renaming `Withdraw` -> `WithdrawUnallocatedRewards`, which will remove the need for doc comment above

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +            withdrawableByDao = getContractBalance() - claimableByVoters;
This function's body can be reduced to just this line and the if-else removed. Logic should be the same

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +        if( withdrawableByDao < rewardsSum ) revert InsufficientContractBalance();
Should this be `if(getContractBalance() < rewardsSum)`?

EDIT: Ahh okay never mind I get it now. `withdrawableByDao` is actually the balance of the contract which hasn't _already_ been allocated, which is what needs to at least equal to `rewardsSum` in order to successfully allocate.

On that note I'd suggest a rename of `withdrawableByDao` to `unallocatedFunds` or similar.

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +        for (uint i = 0; i < rewards.length; i++) {
This loop can be combined with the loop on `111`. The `revert` on `114` will undo any updates if run, so you don't need to worry about updating those values before `rewardsSum` is ready to be validated

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +        if( balanceOf[msg.sender] == 0 ) revert InsufficientVoterBalance();
Hmm minor nitpick here but it occurs to me just now that it probably makes more sense to rename `InsufficientVoterBalance` to something more along the lines of `NoClaimableReward`, since claiming is an "all or nothing" process. Really not that important though

2022-09-30 11:31 UTC, DarksightKellar commented on contracts/Collection.sol
> +        if( withdrawableByDao <= claimableByVoters ) revert BalanceClaimableByVoters();
I'm still trying to understand this check here.

If `withdrawableByDao` is equal to `claimableByVoters`, why can't it be withdrawn?

I'm also wondering what happens if the DAO withdraws unallocated funds, and this contract receives a token amount that is less than `claimableByVoters`, some time passed without any reward allocation or claims, and the DAO attempts to withdraw again. This would cause a revert here even though the balance is NOT in fact claimable.

Also how is `withdrawableByDao` being updated when tokens are sent over to this contract?

I might be missing some context here, of course, and this is all intended behaviour. So some insight would be much appreciated.

2022-09-30 11:31 UTC, DarksightKellar commented on tsconfig.json
> +, "Test.ts", "Test_old.ts", "Test_old copy.ts", "Test_old.ts"    ],
Probably no need for `*_old` and `*copy` references.

2022-09-30 11:31 UTC, DarksightKellar commented on test/Test.ts
> +let zero = ethers.constants.Zero;
Recommend `const` here

2022-09-30 11:31 UTC, DarksightKellar commented on test/Test.ts
> +        it("should set withdrawableByDao to match rewards that have not been allocated to voters", async () => {
Can you also add a test for the behaviour of `withdrawableByDao` under these conditions?

2022-09-30 11:31 UTC, DarksightKellar commented on test/Test.ts
> +          await expect(collection.connect(sarcoDao).setRewards(rewards)).to.be.revertedWith("InsufficientContractBalance")
Another thought -- maybe rename `setRewards` to `allocateRewards`?

2022-09-30 11:31 UTC, DarksightKellar commented on test/Test.ts
> +      context("2 voters successfully claim 10 SARCO each", () => {
I wouldn't use actual numbers/values in these descriptions. 
"2 voters successfully claim the SARCO allocated to them" has a more generalised read than "2 voters successfully claim 10 SARCO each." 

It just so happens that in the test to demonstrate that the description is true, 10 SARCO was used.

2022-09-30 11:31 UTC, DarksightKellar commented on test/Test.ts
> +          expect(await sarco.balanceOf(sarcoDao.address)).to.equal(withdrawableByDao)
I would add one or two more `expect`s over here to verify that the contract's claimable rewards have been untouched

2022-09-30 11:31 UTC, DarksightKellar commented on test/Test.ts
> +        it("should revert if balance of contract is equal to claimable voter rewards", async () => {
We should probably think through some more usecases and paths to test for here. This ties in to my comment on `Collection.sol`'s line `145`

2022-10-03 08:10 UTC, solidoracle commented on test/utils/helpers.ts
> +export function sum(rewards: any) {
Do you mean defining the interface Rewards before the function?

2022-10-03 09:27 UTC, solidoracle commented on contracts/Collection.sol
> +        if( withdrawableByDao <= claimableByVoters ) revert BalanceClaimableByVoters();
I agree with your comment, if withdrawableByDao is equal to claimableByVoters the DAO should still be able to withdraw the amount. We could set the condition to revert if withdrawableByDao == 0? However this doesn't solve your second point, as calling the updateInternalBalance() function would result in setting withdrawableByDao to a negative number.

withdrawableByDao is updated when setRewards() is called, as it calls updateInternalBalance()

2022-10-03 09:35 UTC, solidoracle commented on test/Test.ts
> +let zero = ethers.constants.Zero;
The SignerWithAddress need to be initialised if setting them to const; adding ethers.getSigners() however is a promise

2022-10-03 10:27 UTC, solidoracle commented on test/Test.ts
> +        it("should set withdrawableByDao to match rewards that have not been allocated to voters", async () => {
What conditions do you mean here?

2022-10-03 11:47 UTC, solidoracle commented on contracts/Collection.sol
> +        for (uint i = 0; i < rewards.length; i++) {
By combining these loops withdrawableByDao and claimableByVoters need to get calculated outside the loop with the rewardsSum amount

2022-10-03 13:32 UTC, solidoracle commented on contracts/Collection.sol
> +        if( withdrawableByDao < rewardsSum ) revert InsufficientContractBalance();
I renamed withdrawableByDao to unallocatedRewards

2022-10-04 09:19 UTC, solidoracle commented on test/utils/helpers.ts
> +let zero = ethers.constants.Zero;
I also added the export prefix so I can import it in test file as well

2022-10-04 09:37 UTC, solidoracle commented on test/Test.ts
> +        it("should revert if balance of contract is equal to claimable voter rewards", async () => {
I added the test for withdrawing multiple times when additional rewards are sent to the contract that remain unallocated.

All comments above have been addressed.

2022-10-04 11:47 UTC, DarksightKellar approved these changes

2022-10-04 11:47 UTC, DarksightKellar commented
Thanks for all the updates!

2022-10-04 13:03 UTC, sethhrbek commented
This code is on main, so closing.

2022-10-04 13:03 UTC, closed without merging